### ISSUE TITLE
Question: How to config?

### ISSUE THREAD

**Issue by dmytrodubinin** [artempyanykh/marksman#116]
I try to use marksman in neovim but I have many problems. There are some of my questions:

1. **How to config?** I can't find any instructions and shortcuts list in github page. For example I use default settings and when I try to add links into document, links inserted incorrect:
[Screencast from 2022-11-27 10-17-16.webm](https://user-images.githubusercontent.com/8066458/204125587-7eacd309-c76b-4b12-aba6-bd0566801dcc.webm)
I try to insert link into file `atomic_habits`, but marksman insert icorrect link `atomic-habits` and also show diagnostics error.
How to config links formatting?

2. **Why diagnostics show errors in correct links?** It's the same as previous. I have correct links into others files, but marksman show errors:
[Screencast from 2022-11-27 10-22-55.webm](https://user-images.githubusercontent.com/8066458/204125756-ef4d14c0-c044-4459-9e09-776419d8c3d1.webm)

Basic question is configuration for links and diagnostics. I want to use my own links format and want to config shortcuts for it.

Please explain me how to config or show me detail instruction for it.

**Comment by artempyanykh** [comment]
Thanks for raising this @dmytrodubinin!
Unfortunately, Github doesn't open the screencasts, so I can't see what's going on in the bug report. 

Assuming you're talking about the wiki links, currently they use a document's title rather than a filename. So a link to a document `atomic_habbits.md` with a title `# Atomic Habbits` would be `[[atomic-habbits]]` (title turned into a slug).

But as for the question about link style configuration, this is in progress in #117. It's progressing nicely, so hopefully soon.

**Comment by dmytrodubinin** [comment]
Thanks for the answer!
