### ISSUE TITLE
Support wiki links titles

### ISSUE THREAD

**Issue by gmcusaro** [artempyanykh/marksman#136]
As mentioned in docs:

> By default Marksman uses a document title's slug when referencing a document, however there is an configuration setting to use a file name or a file path instead.

and in [this reply](https://github.com/artempyanykh/marksman/issues/122#issuecomment-1348312210), like in Obsidian and Foam it could be really useful to add a `|` for a title/alias to the slug or filename/path:

`[[destination|title]]`

Example:
`Check my [[short-bio|bio]]`

Preview:
`Check my bio`

**Comment by artempyanykh** [comment]
Thanks for raising this @gmcusaro. Supporting titles in wiki-links definitely makes sense.

**Comment by eguiraud** [comment]
Hello, I don't know much F# but I wouldn't mind giving this a shot if it's just a matter of changing a regex or similar and you can point me to the relevant section of the code :grimacing:

**Comment by artempyanykh** [comment]
@eguiraud sounds good! Not quite tweaking a regex experience, because the parsing library wants to do it in a 'char-by-char matching' way, but the relevant section of the parser is [this one](https://github.com/artempyanykh/marksman/blob/main/Marksman/Parser.fs#L66-L163) And you would probably want to tweak [this definition of a wiki link](https://github.com/artempyanykh/marksman/blob/main/Marksman/Cst.fs#L28) to also include the title node.

LMK how it goes!

**Comment by eguiraud** [comment]
Hello, yes I can try to give this a shot either this week or the next.

**Comment by tjex** [comment]
year made ✅. thanks @eguiraud

**Comment by eguiraud** [comment]
Happy to help!
