### ISSUE TITLE
Slow performance with large workspaces (~3k files)

### ISSUE THREAD

**Issue by Feel-ix-343** [artempyanykh/marksman#197]
I am writing notes in a vault with 2800 notes (neovim) and marksman is unusably slow. 

These are the stats:
![image](https://user-images.githubusercontent.com/88951499/232315069-8068647e-f914-4b2b-bbac-69fa89ce7e82.png)

It takes roughly 1 minute and 8 seconds for changes to populate in the diagnostics

Other info
- Using mason-lspconfig for automatic configuration
- Installation using mason nvim

**Comment by Feel-ix-343** [comment]
I think the only solution is the rewrite in rust...

**Comment by artempyanykh** [comment]
Hi @Feel-ix-343! That's quite a vault you have. Thanks for raising this problem. It would help to be more specific:
1. Do you see performance problems with diagnostics only?
2. How about other bits of functionality: 
    * is the server responsive when you type? 
    * Do you get responsive go-to-def, hover? 
    * How about completion?
 3. What is `marksman --version`?

> I think the only solution is the rewrite in rust...

I like your sense of humour, my friend! I previously wrote about ways to improve general performance by an order of magnitude [in this comment](https://github.com/artempyanykh/marksman/issues/179#issuecomment-1490748522) (where I also touched on Rust).

When it comes to **diagnostics in particular**, it's not too hard to make it work faster by improving the asymptotic of the algorithm. More specifically,
* currently, cross-file link resolution is linear in the number of files ([ref](https://github.com/artempyanykh/marksman/blob/main/Marksman/Refs.fs#L222-L223)). 
* It shouldn't be too hard to make a patch to make link resolution effectively constant time. Something like a suffix tree instead of a linear scan to match paths, and hash tables for title-based resolution.

All-in-all there are many low hanging fruit that can drastically improve performance and **I'd happily accept such patches**.

**Comment by Feel-ix-343** [comment]
Version:
![image](https://user-images.githubusercontent.com/88951499/232346392-1809f6d1-96e3-422a-8722-ccee7a90c7c4.png)

Performance details: I just tracked the time for the CPU to return from 100%
![image](https://user-images.githubusercontent.com/88951499/232346445-d1d129b0-e55f-44e4-b809-6994da567340.png)

I think the features that this involves are the
- Diagnostics
- maybe completion? THere are only text completions
![image](https://user-images.githubusercontent.com/88951499/232346559-be6c1f60-af00-49e7-8a02-ded28184d7f3.png)
- Maybe the other features? I don't know I haven't used them yet

**Comment by Feel-ix-343** [comment]
Then after I make change to the file, I am left with straggling diagnostics like this one
![image](https://user-images.githubusercontent.com/88951499/232346839-47fc06c4-755b-477c-b3d4-a7e0dadef08e.png)

**Comment by artempyanykh** [comment]
@Feel-ix-343 if you fancy building Marksman from source, you may want to try #212 -- I want to tweak a couple more things in the PR but perf improvements are already pretty substantial especially for larger workspaces.

**Comment by artempyanykh** [comment]
The [2023-06-01](https://github.com/artempyanykh/marksman/releases/tag/2023-06-01) version has been released. Feel free to give it a spin!

**Comment by Feel-ix-343** [comment]
Thank you so much for working on that update

Unfortunately now I am getting no diagnostics on my large vault, but I am on a smaller test vault (and also no completion #204 )

**Comment by artempyanykh** [comment]
@Feel-ix-343 thanks! Commented on #204 but if you could run marksman with full verbosity and post LSP logs here, that would be a great help!

**Comment by Feel-ix-343** [comment]
I think this was fixed btw

**Comment by Feel-ix-343** [comment]
(and BTW, I wasn't kidding about the rust part[!](https://github.com/Feel-ix-343/moxide)) (In all seriousness, I love markdown and this project; thank you for some inspiration; my lsp is mainly for fun and personal use, and I am testing it against marksman for correctness lol)

**Comment by artempyanykh** [comment]
Cool project! Hope you'll have fun with moxide @Feel-ix-343!

As a fun and somewhat ironic piece of historical context: Marksman that you see now is actually a v2; v1 was written in Rust. I think this is the last Rust commit before F# rewrite started: https://github.com/artempyanykh/marksman/tree/35fb4ec15a32c9a0afc84364c4af6c1034c29a47 Perhaps, you'll find some inspiration in that codebase.

**Comment by Feel-ix-343** [comment]
Oh I remember seeing this; I will for sure read through the code. Thank you so much for reminding me about that!
