### ISSUE TITLE
Completions by Marksman dont't work at all in Neovim (macOS)

### ISSUE THREAD

**Issue by mnddm** [artempyanykh/marksman#204]
Hello there!

I try to use Marksman in Neovim 0.9. I've configured cmp and LSP correctly (tested on other filetypes), but marksman don't want to show me the completions from the LSP. And looks like hover doesn't work too.

How I tested:

1. I've created two files `test1.md` and `test2.md`; both placed in the same directory with `.git`.
2. Add the header "##header" to `test1` and try to make a link to it in `test2`.
3. All these completions didn't work (`|`—the cursor):
    3.1. `[[te|]]`
    3.2. `[[test1#h|]]`
    3.4. `[my-link](te|)`
    3.5. `[my-link](test1#h|)`

Here is example that shows no completions by LSP (the should be in the first place).
![1](https://github.com/artempyanykh/marksman/assets/124259287/82247fee-3ba7-44cc-a2e7-6ed4855e3b1c)

What work:
1. In the same time the _diagnostics_ works: when I delete any symbol from correct link I receive the warning about incorrect link (sorry but not sure it's because of `marksman` or other linter I use). 
2. And following by the link by (`vim.lsp.buf.definition()`).

**Comment by artempyanykh** [comment]
Hi @mnddm! Thanks for trying out marksman. Based on what you wrote above, I can assume that the problem is that you need/expect a different completion style.

By default Marksman uses level 1 header as a link to the document, e.g.
```
# This is the title

Foo bar

## Subtitle
```

What you want is probably a completion by file name. See the Configuration section in the README on how to configure completion style.

LMK if it helps!

**Comment by mnddm** [comment]
Hi, @artempyanykh, thanks for help. Unfortunately it didn't help. I've followed the instructions and changed the `wiki.style` to `file-stem` in project `.marksman.toml` but completions still don't work. Link diagnostics (i.e. is it correct link?/is it correct link with header?) and `vim.lsp.buf.definition()` work as expected.

**Comment by BingCoke** [comment]
sound like this issue #160 ?

**Comment by mnddm** [comment]
Hi @BingCoke. Tested without spaces, completions provider by LSP still didn't work.

**Comment by BingCoke** [comment]
> Hi @BingCoke. Tested without spaces, completions provider by LSP still didn't work.

I mean this looks like a bug waiting to be fixed

**Comment by mnddm** [comment]
> I mean this looks like a bug waiting to be fixed

Tested these scenarios and all works:

1. Create "f1.md" with `## Header with spaces` and second file with link `[[f1#Header with spaces]]` (diagnostics and navigate into works, completions not).
2. Create "f2 with spaces filename.md" with `## Header` and second file with link `[[f2 with spaces filename#Header]]` (diagnostics and navigate into works, completions not).

**Comment by mediapathic** [comment]
I believe I am having the same, or similar, issue. Also on mac, using the Astronvim framework, new install, so fairly clean. I know marksman is installed and working generally because I can do symbol searches, but no completions (spaces or no) seem to work. 

@mnddm this doesn't solve the issue, but a workaround I've found: starting a link with `./`, in my setup, triggers a completion based on filepath, unrelated to marksman. This might help you till we figure out this issue.

**Comment by Feel-ix-343** [comment]
Same here on arch and config https://github.com/Feel-ix-343/Neovim-Config

**Comment by artempyanykh** [comment]
@Feel-ix-343 thanks for posting you config! What would also be really helpful is if you could run marksman with verbose logs `marksman server -v=5` (or something along this lines) and paste the LSP logs here. It seems that the problem affects a few people but I so far couldn't reproduce.

**Comment by artempyanykh** [comment]
@mnddm do you by any chance have something like [this](https://github.com/hrsh7th/nvim-cmp/blob/5dce1b778b85c717f6614e3f4da45e9f19f54435/doc/cmp.txt#L663) in your nvim config? I recently had a quick debug session with @antonk52 who had a similar problem (no completions) and the culprit was that extra candidate filtering on the neovim's side.

**Comment by Noobvelopper** [comment]
> @mnddm do you by any chance have something like [this](https://github.com/hrsh7th/nvim-cmp/blob/5dce1b778b85c717f6614e3f4da45e9f19f54435/doc/cmp.txt#L663) in your nvim config? I recently had a quick debug session with @antonk52 who had a similar problem (no completions) and the culprit was that extra candidate filtering on the neovim's side.

I had this exact issue, and this fixed it for me. Thank you !

**Comment by vcavallo** [comment]
I'm having no luck with NVIM 0.9.5 and coc.vim version 0.0.82. 

- The extension won't enable on its own (have to run `:CocList extensions`, then hit <return> to toggle it on
- After doing the above, Coc won't find the marksman command unless i add `"marksman.customCommand": "/home/<my-user>/.nix-profile/bin/marksman"`
- Even after doing the above and marksman is running (I'm getting warnings inline in files for nonexistent linked files), I don't get completion on [[ or any other features.

**Comment by dnjp** [comment]
> Same here on arch and config https://github.com/Feel-ix-343/Neovim-Config

I just ran into this issue myself. It turns out the cause of the issue is due was due to a configuration error on my end. As you can see in the example config that @Feel-ix-343 shared, the [attach and capabilities](https://github.com/Feel-ix-343/Neovim-Config/blob/main/lua/plugin/LspSetup.lua#L545-L546) options are set for other LSP servers, but not for [marksman](https://github.com/Feel-ix-343/Neovim-Config/blob/main/lua/plugin/LspSetup.lua#L534). The solution is thankfully as simple as making sure these options are set in the `setup` config like this:
```
lspconfig.marksman.setup{
  on_attach = LspOnAttach,
  capabilities = LspCapabilities,
}
```
