### ISSUE TITLE
Neovim LSP Installation error

### ISSUE THREAD

**Issue by dmytrodubinin** [artempyanykh/marksman#225]
I cant install marksman by `:LspInstall marksman`, get an error:
```
 Downloading file "https://github.com/artempyanykh/marksman/releases/download/2023-06-23/marksman-linux"...
        ...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/artempyanykh/marksman/releases/download/2023-06-23/marksman-linux".
        spawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 40
```

It seems like download link is incorrect. The problem appear only with marksman
![image](https://github.com/artempyanykh/marksman/assets/8066458/4a57edc8-7613-4d59-9006-29a8d620c1e0)

**Comment by artempyanykh** [comment]
The artifact names for linux have changed since now we produce binaries for both x86 and for aarch64.

@dmytrodubinin are you using https://github.com/williamboman/nvim-lsp-installer? nvim-lsp-installer has been deprecated in a while in favor of mason-nvim. The latter is maintained and should have the right paths.

**Comment by dmytrodubinin** [comment]
Ok, thanks for quickly response.
It seems time to move into mason-nvim :smile:
