### ISSUE TITLE
Support references and completions for nested tags

### ISSUE THREAD

**Issue by Gelio** [artempyanykh/marksman#267]
Support for completions and references for regular (non-nested) tags was added in https://github.com/artempyanykh/marksman/pull/262. This means that tags such as `#work`, `#home` can now be autocompleted (e.g. typing `#h` provides a completion for `#home`, and looking for LSP references for `#home` returns all the occurrences of this tag in the workspace).

Obsidian supports [nested tags](https://help.obsidian.md/Editing+and+formatting/Tags#Nested%20tags), such as `#home/chore`, `#work/meeting`. A nested tag consists of multiple parts separated by a slash. It makes it possible to further characterize the document and group tags together (e.g. `#work/meeting`, `#work/task`, `#work/administrative`, all belong to the same `#work` top-level tag).

At the moment, completions only support regular tags (marksman does not list `#work/meeting` as a completion when typing `#wor`, and checking references of `#work/meeting` returns no results).

It would be great if completions and references support for added for nested tags, the same way it works for top level tags.

## Specific requirements

Let's consider the following document:

```md
Today I was at #work:

- #work/meeting with Dan
- #work/meeting with Lee
- Completed 5 #work/task
```

Let's assume this is the only document in the workspace.

Requirements:

1. When the cursor is at the word `meeting` in `#work/meeting`, when asking for references, marksman should return only the two `#work/meeting` tags. No other `#work` tags should be returned.
2. When the cursor is at the word `work` in `#work/meeting`, when asking for references, marksman should return all the `#work` top-level and nested `#work/*` tags in the document (there are 4 in total: 1 top-level tag and 3 nested tags).
3. When typing a new list item and typing the word `#wo`, marksman should list the following completions: `#work`, `#work/meeting`, `#work/task`.
3. When typing a new list item and typing the word `#work/m`, marksman should list the following completions: `#work/meeting`.

## Multiple-level nested tags

It would be nice to also support tags nested with multiple levels, such as: `#work/meeting/long`.

**Comment by TheBlob42** [comment]
Currently a tag is defined as the hash sign `#` followed by alphanumeric characters, dashes and underscores. Everything else (including the `/`) ends the tag ([here](https://github.com/artempyanykh/marksman/blob/main/Marksman/Parser.fs#L56)). There we could add the slash to allow it being part of a tag which would solve `1.` and `4.`

`3.` would also be done if your workspace also contains the `#work` tag somewhere (without any nesting)

The point about references depending on the cursor position `2.` seems a little more complicated, since currently Marksman gets the "whole" element at cursor position ([here](https://github.com/artempyanykh/marksman/blob/main/Marksman/Server.fs#L877)) and then checks for references for it. This would need adaption to check for the exact cursor position and return only the matching "parts" of the nested tag if applicable

**Comment by Gelio** [comment]
Thanks for the writeup! Looks like getting the majority o the use-cases covered should be relatively simple. Unfortunately, I don't have F# experience so I won't be able to contribute it reasonably :/
