### ISSUE TITLE
TOC formatting vs prettier

### ISSUE THREAD

**Issue by artempyanykh** [artempyanykh/marksman#60]
A continuation of https://github.com/artempyanykh/marksman/issues/52#issuecomment-1229181425

The problem is that the current TOC formatting doesn't play nicely with prettier.

There is an issue in prettier https://github.com/prettier/prettier/issues/10128 about this, but right now it's causing friction.

A potential workaround is to add newlines after/before <--!toc:xx--> marker.

/cc @keynmol @David-Else

**Comment by David-Else** [comment]
> Both adding newlines and preserving them when detecting TOC is probably not a massive amount of work, I just feel it will be done for the wrong reasons (circumventing a 3rd party plugin behaviour which is seen as a problem by others)

I think the workaround looks better anyway, and if Prettier changes to not create the newline in the future it would not cause any problems or create any regressions? You can create as many new lines before and after the TOC as you want and Prettier just formats it back to be one line above and below.

Pandoc seems to have no problem understanding the toc with spaces either side:
```
pandoc ./example.md -f markdown -t html -o ./example.html
```
@keynmol  I see what you are saying about the workaround, but that issue is a year old, I don't think anyone else is concerned about it other than the three people in that thread.

**Comment by artempyanykh** [comment]
#67 makes the TOC ignore whitespace when checking if it's up to date. This should resolve this problem with prettier formatting always triggering a code action to Update TOC. I'll push out the release shortly.

**Comment by David-Else** [comment]
@artempyanykh I tested it, works great, cheers!
