### ISSUE TITLE
Server never initializes if no workspaceFolders are given

### ISSUE THREAD

**Issue by jwortmann** [artempyanykh/marksman#66]
The server never responds to the initialize request from the client, if it contains `workspaceFolders: null`.

From the LSP specs:
```typescript
        /**
	 * The workspace folders configured in the client when the server starts.
	 * This property is only available if the client supports workspace folders.
	 * It can be `null` if the client supports workspace folders but none are
	 * configured.
	 *
	 * @since 3.6.0
	 */
	workspaceFolders?: [WorkspaceFolder](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFolder)[] | null;
```

**Comment by artempyanykh** [comment]
@jwortmann thanks for reporting! I think you may have hit the problem that #68 addresses (which is about initialization). Please try https://github.com/artempyanykh/marksman/releases/tag/2022-09-02 and let me know if the initialization issue is gone.

When it comes to 'single file mode', some functionality like document symbols and reference links can work in a single file mode but the rest (workspace symbols, renames, cross-links, etc) really needs a "folder".

However, the important bit here is that the 'single file mode' is not a part of the LSP spec. I'm not sure how things are configured in sublime, but I'd recommend setting a folder for you markdown -- this'll give the best experience.

If you do care about the 'single file mode' feel free to open a separate issue specifically about this. I'm generally OK with the idea of having some custom bits to emulate 'single file mode', but since it's not part of the spec it's not very high on my priority list.

**Comment by jfcherng** [comment]
Hi @artempyanykh, with 2022-09-02 and single file mode, the server does start but I don't see it provide anything but just return `[]` and `None` for everything.

**Comment by rwols** [comment]
I believe by “single file mode” is meant that workspaceFolders is null in the initialize request, which by the spec is valid.

**Comment by jwortmann** [comment]
I can confirm what @jfcherng wrote.

> However, the important bit here is that the 'single file mode' is not a part of the LSP spec.

Right, this kind of expression is not explicitly mentioned in the LSP specs, but neither is 'project mode' or 'workspace mode' or whatever. But if you look at the description for the [Workspace folders request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders), there it is written that it

> Returns `null` in the response if only a single file is open in the tool. Returns an empty array if a workspace is open but no folders are configured.

So at least they describe the possibility that only a single file is open in the editor. And there are servers like Microsoft's *vscode-css-languageserver* or *vscode-html-languageserver* which seem to operate exclusively in 'single file mode', i.e. they apparently don't care whether workspaceFolders (or rootUri) are provided in the initialize request or not. Probably because CSS and HTML are languages which usually don't have any strict project structure or configuration files associated with the source code. And I would expect the same for Markdown. For example it is clear that relative links to other documents should be interpreted relative to the current document. And I think it should be possible to provide most of the features, e.g. "Document Symbols" even without workspaceFolders.

Anyway, since the latest server version correctly responds to the initialize request, we can close this now. Thanks for the fix!

**Comment by artempyanykh** [comment]
@jfcherng right now Marksman does need a root/folder and doesn't provide a single-file mode. 

But now that I'm thinking a bit more about this, it seems that it'd be quite convenient and a better/less confusing UX overall. I've created a separate issue for this #69
