### ISSUE TITLE
Reference link labels should be case-insensitive

### ISSUE THREAD

**Issue by weakish** [artempyanykh/marksman#73]
First, marksman treat link labels case sensitive.
For exmaple, the following markdown triggers a false positive warning.

```markdown
[A][]

[a]: https://example.com
```

According to [John Gruber's canonical description of Markdown's syntax](https://daringfireball.net/projects/markdown/syntax#link),
link labels are case insensitive.

> Link definition names may consist of letters, numbers, spaces, and punctuation — but they are *not* case sensitive. E.g. these two links:

>     [link text][a]
>     [link text][A]

> are equivalent.

Second, marksman does not recognize [shortcut reference links][shortcut].
For example, the following markdown does not trigger any warnings.

```markdown
[b]
```

Shortcut reference links were introduced by Gruber himself in a beta version of Markdown.pl, but never included in the official syntax description.
Most popular markdown parsers support shortcut referneces.
Also, CommonMark includes shortcut reference links in its [specification][shortcut].

[shortcut]: https://spec.commonmark.org/0.30/#shortcut-reference-link

```sh
; marksman --version
1.0.0-19de239
```

![vscode-screenshot](https://user-images.githubusercontent.com/114114/188328607-dec93556-4297-4150-8d01-3cf6acc143de.png)

**Comment by artempyanykh** [comment]
Thanks for reporting @weakish! Case sensitivity in link resolution should be fixed; I’ll look into it.

Re: shortcut links, shortcuts  a-la `[foo]` work when it comes to go-to definition, completion, etc (modulo case-sensitivity). There’s no diagnostic for shortcut links (which is IIUC the problem you mentioned above) because generally you can’t tell if something is supposed to be a shortcut link or not: it’s a shortcut link when there’s a corresponding link definition; otherwise it’s just text, e.g.:
```
* [TODO] Do A
* [DONE] Do B
* [REF] Do C

[REF]: url.com
```

If we emit diagnostics for every `[foo]` without a matching link definition `[foo]: bar` it’d create quite a bit of noise.
