### ISSUE TITLE
Root directory not found

### ISSUE THREAD

**Issue by Leo-Zarni01** [artempyanykh/marksman#82]
Hello, so I am currently using WSL 2 Ubuntu, and I am having this error as shown in the pic when I run `LspInfo` on Neovim. I downloaded the latest release via curl, renamed the binary and even placed it inside my PATH folder. But for some reason, it seems like LSP is not properly detecting Marksman as completion and other features not seem to work. Here's the error message below with some additional images as reference:

![image](https://user-images.githubusercontent.com/50450659/189910598-84f0413b-33ad-4d7d-a9e3-aba3c23b04ad.png)

In my bin folder:
![image](https://user-images.githubusercontent.com/50450659/189910727-eb8922c0-a69c-4d6a-8058-aca16da9a379.png)

In my `.bashrc` file:
![image](https://user-images.githubusercontent.com/50450659/189910830-2f8582ea-3387-46d7-8719-4aea764d3c49.png)

**Comment by Leo-Zarni01** [comment]
And this is my setup code in `init.lua` :
![image](https://user-images.githubusercontent.com/50450659/189911728-fd8ccab3-5e49-4d93-8f57-d1e8226b0af7.png)

**Comment by artempyanykh** [comment]
@Leo-Zarni01 I'm assuming your files are not under git? If so, could you put `.marksman.toml` at the root folder where your markdown files are?

The reason is neovim/LSP need a "folder" to start the LSP server on. More about this here https://github.com/artempyanykh/marksman#workspace-folders-project-roots-and-single-file-mode

**Comment by Leo-Zarni01** [comment]
Hi it seems to work now thank you so much!

**Comment by artempyanykh** [comment]
Happy to hear it works!
