### ISSUE TITLE
Does marksman support lint?

### ISSUE THREAD

**Issue by seagle0128** [artempyanykh/marksman#84]
Hi, thanks for the great lang server for markdown.
I am wondering if marksman support markdownlint or other lint tools/plugins?

**Comment by artempyanykh** [comment]
Hey @seagle0128, thanks for the kind words! I didn't really think about getting into the whole "style checking" business.

AFAIK many editors now support multiple LSP servers per file so you can have e.g. in neovim:
1) marksman for markdown "intellisence",
2) ltex-ls for spell checking,
3) markdownlint via null-ls for style checking,
4) prettier via null-ls for formatting.

Similar setup is possible in Emacs too. AFAIU Helix doesn't support multi-server yet, but it's in the works.

The point is, there's number of mature tools that already have various editor integrations, so I didn't feel too compelled to spend time duplicating the work. With that said, I do understand that it'd be very convenient if there was just 1 tool, rather than 4 😄

Anyhow, TL;DR: there's no style checking functionality in Marksman. What I spend my time on is more around markdown "intellisence". But I'm happy to take contributions 🙂

**Comment by seagle0128** [comment]
> The point is, there's number of mature tools that already have various editor integrations

I agree. AFAIK, many lang servers leverage the plugin mechanism to integrate other tools to achieve. 

Anyway, thanks for your detailed explanation! I am closing it.
